# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run test --if-present
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        GIT_AUTHOR_NAME: ${{ github.repository_owner }}
        GIT_AUTHOR_EMAIL: mmatyi1999@gmail.com
        GIT_COMMITTER_NAME: ${{ github.repository_owner }}
        GIT_COMMITTER_EMAIL: mmatyi1999@gmail.com
